### ISSUE TITLE
getUser only works when setting a variable to the result.

### ISSUE THREAD

**Issue by amazinigmech2418** [kyleplo/scratchOn#12]

**Comment by amazinigmech2418** [comment]
The same is true for all other get requests with the scratchOn.

**Comment by kyleplo** [comment]
No, you can also use:
```javascript
scratchOn.getUser("kyleplo").then(function (u){
   console.log(u)
});
```
and the console says:
![image](https://user-images.githubusercontent.com/31634240/43469902-3a6669c6-94b5-11e8-9a3b-a749fcfffa14.png)
