### ISSUE TITLE
There is a lot of code repetition!

### ISSUE THREAD

**Issue by towerofnix** [kyleplo/scratchOn#7]
I think it's pretty obvious that there is a *lot* of copy-pasted code in here. Take a look at this brief snippet of the code, which is just four functions!

https://github.com/kyleplo/scratchOn/blob/23e6ca463cfeeb0e547651d9582b3a495ad5dee4/scratchon.js#L206-L253

I think it would be really handy for anybody who wants to contribute (including yourself, really) if there were less copy-pasted code. Perhaps you could create a "helper" function for these, which takes parameters that are specific to each individual function and then does all the work? That would look something like this:

```js
async getProjectsHelper(urlPart){
  var projects = await scratchOn.scratchGet(this.endpoint, this.username, urlPart, "GET");
  if(projects === "FetchError"){
     return [];
  };
  var projectList = [];
  for(var i = 0;i < projects.length;i++){
     var that = projects[i];
     projectList.push(new Project(that.id,((that.author ? that.author.username : false) ? that.author.username : "ScratchOnMissingUser"),((that.author ? that.author.id : false) ? that.author.id : -1),that.title,{instructions: that.instructions,description: that.description},that.history,that.stats,that.remix,that.image));
  };
  return projectList;
}
```

Then you could use it like this:

```js
getProjects(offset,limit){
  return this.getProjectsHelper("/projects/?offset=" + (offset ? offset : 0) + "&limit=" + (limit ? limit : 40));
}
getAllProjects(){
  return this.getProjectsHelper("/projects/");
}
getFavorites(offset,limit){
  return this.getProjectsHelper("/favorites/?offset=" + (offset ? offset : 0) + "&limit=" + (limit ? limit : 40));
}
getAllFavorites(){
  return this.getProjectsHelper("/favorites/");
}
```

Of course, there are a lot of other ways to make helper functions. This one is just an example to get you started.

**Comment by kyleplo** [comment]
@towerofnix Do you want to work on this?

**Comment by towerofnix** [comment]
@kyleplo It's a pretty big task, and I'm quite busy with life and my own things.. I think I'd rather stick to code review comments than actually making PRs to this, sorry.

(Btw, did you notice that there's actually a bug in the code I wrote for `getProjectsHelper`? You see, it *always* uses `scratchGet`, never `scratchGetAll`: so functions like `getAllProjects` and `getAllFavorites` wouldn't work. You'd need to either make another helper function, `getAllProjectsHelper`, or pass an argument for whether to use `getProjects` or `getAllProjects`.)

**Comment by kyleplo** [comment]
@towerofnix Ok, I'm working on this.
